name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Build shared object
        run: make build
      - name: Run FTW tests
        run: make ftw
      - name: Run e2e tests
        run: make e2e
      - name: Generate Release Notes
        id: notes
        uses: theory/changelog-version-notes-action@v0.1.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: envoy-coraza
          push: true
          tags: ghcr.io/united-security-providers/envoy-coraza:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Release Candidate
        uses: softprops/action-gh-release@v3
        if: ${{ contains(github.ref_name, '-rc') }}
        with:
          body_path: '${{ steps.notes.outputs.file }}'
          generate_release_notes: false
          prerelease: true
          files: |
            CHANGELOG.md
            LICENSE
            build/coraza-waf.so
      - name: Final Release
        uses: softprops/action-gh-release@v3
        if: ${{ !contains(github.ref_name, '-rc') }}
        with:
          body_path: '${{ steps.notes.outputs.file }}'
          generate_release_notes: false
          prerelease: false
          files: |
            CHANGELOG.md
            LICENSE
            build/coraza-waf.so
